cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7245125
  lightness: 0.4011815
  brandStrength: 0.6858217
  brandColors:
    - '#FFFFFF'
    - '#051344'
    - '#66A4B3'
    - '#FDCC99'
    - '#4542AA'
  rhythmicContrast: 0.08968847
typography_spectrum: 0.5934479
layout_spectrum: 0.3281418
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Mick Darling dot com
