name: Mick Darling dot com
favicon: null
layout_spectrum: 0.61062
typography_spectrum: 0.28475
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#051344'
    - '#66A4B3'
    - '#FDCC99'
    - '#4542AA'
  brandStrength: 0.6875
  lightness: 0.4011815
  saturation: 0.7245125
  rhythmicContrast: 0.08968847
purpose: []
